### PR TITLE
Features/19

### PR DESCRIPTION
**Pull request by sorobon**

### CODE REVIEW

**Comment by dortegau** [comment]
What a nice profile picture! xd

**Review by dortegau — APPROVED** [review]
Good job!

**Comment by dortegau** [comment]
@sorobon you should add your changes to the changelog! :)

Update the changelog!

**Comment by sorobon** [comment]
68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3231393238392f323136303837312f30666636633134302d393462662d313165332d383735342d6530343734383365626361312e6a7067

**Review by jmonterrubio — APPROVED** [review]
Yeah!

**Pull request merged**
